// Executable InDesign-DOM simulation: validates orchestration, not actual typesetting.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../Layout-Report.jsx'),'utf8').replace(/^#target.*$/m,'');
function run(overrides={},scenario={}){
    const files={},events=[],created=[],fonts=[];let doc;
    function list(items=[]){items.item=i=>items[i];items.itemByName=name=>items.find(x=>x.name===name)||{isValid:false};items.everyItem=()=>new Proxy({getElements:()=>items.slice()},{set(t,p,v){for(const item of items)item[p]=v;return true;},get(t,p){if(p==='texts')return {everyItem:()=>new Proxy({},{set(_,k,v){for(const item of items)for(const text of item.texts)text[k]=v;return true;}})};return t[p];}});return new Proxy(items,{get(t,p){if(p==='-1')return t[t.length-1];return Reflect.get(t,p);}});}
    class File {constructor(p){this.fsName=String(p);this.name=path.basename(this.fsName);this.parent={fsName:path.dirname(this.fsName)};this.displayName=this.name;}get exists(){return (scenario.cancel&&this.name==='cancel.request')||/\.(docx|idml)$/.test(this.name)||Object.hasOwn(files,this.fsName);}open(){return true;}write(s){files[this.fsName]=s;}close(){}copy(p){files[p]='font';return true;}}
    class Folder {constructor(p){this.fsName=p;}get exists(){return !this.fsName.endsWith('/Document fonts');}create(){return true;}getFiles(){return [];}}
    class Style {constructor(name){this.name=name;this.isValid=true;}set properties(o){Object.assign(this,o);}}
    const initial=['[None]','Heading 1','Heading 2','Normal'];const styles=list(initial.map(n=>new Style(n)));styles.add=o=>{const s=new Style(o.name);styles.push(s);return s;};
    function paragraph(story,text,index,styleName){const p={contents:text,appliedParagraphStyle:styles.itemByName(styleName),characters:list(Array.from(text).map((c,i)=>({contents:c,index:index+i}))),textStyleRanges:list([]),applyParagraphStyle(s){this.appliedParagraphStyle=s;}};p.insertionPoints=[{get parentTextFrames(){return [story.textContainers[0]];}}];return p;}
    class Story {
        constructor(){this.isValid=true;this.id=created.length+1;this.storyPreferences={};this.textContainers=[];this.tables=list([]);this.allGraphics=list([]);this._text='';this.paragraphs=list([]);this.characters=list([]);const story=this;this.texts=list([{get contents(){return story.contents;},set contents(v){story.contents=v;}}]);created.push(this);}
        get contents(){return this._text;}
        set contents(v){this._text=v;let pos=0;const parts=String(v).split('\r');this.paragraphs=list(parts.map((t,i)=>{const text=t+(i<parts.length-1?'\r':'');const p=paragraph(this,text,pos,'Normal');pos+=text.length;return p;}));this.characters=list(Array.from(v).map((c,i)=>({contents:c,index:i})));}
        get overflows(){return scenario.overset||(!this.isBody&&this.contents.startsWith('فهرست')&&this.paragraphs.length>this.textContainers.length*3);}
    }
    class TextFrame {
        constructor(pg,isHeader=false){this.isValid=true;this.parentPage=pg;this.label=isHeader?(scenario.missingHeader?'':'REPORT_HEADER'):'';this._story=new Story();this._story.textContainers.push(this);this.textFramePreferences={};this.geometricBounds=[];this.insertionPoints={'-1':{get index(){return 100;}}};}
        get parentStory(){return this._story;}
        get contents(){return this._story.contents;}
        set contents(v){this._story.contents=v;}
        set nextTextFrame(next){const old=next._story;created.splice(created.indexOf(old),1);next._story=this._story;this._story.textContainers.push(next);next.insertionPoints['-1']={index:this._story.textContainers.length*100};}
        place(){this._story.isBody=true;this.contents=scenario.noHeadings?'Body':Array.from({length:8},(_,i)=>'Heading '+(i+1)).join('\r');this._story.paragraphs.forEach((p,i)=>p.appliedParagraphStyle=styles.itemByName(i%2?'Heading 2':'Heading 1'));if(scenario.noHeadings)this._story.paragraphs[0].appliedParagraphStyle=styles.itemByName('Normal');if(scenario.inlineImage){const imageParagraph={};const anchor={parentParagraphs:list([imageParagraph])},placeholderParagraph={applyParagraphStyle(s){this.appliedParagraphStyle=s;}};const holder={isValid:true,anchoredObjectSettings:{anchoredPosition:'INLINE_POSITION'},geometricBounds:[0,0,800,800],parent:anchor,parentStory:{paragraphs:list([placeholderParagraph])},textFramePreferences:{},resolve(point){return point==='TOP_LEFT_ANCHOR'?[[0,0]]:[[this.geometricBounds[3],this.geometricBounds[2]]];},resize(_in,_from,_by,values){this.geometricBounds=[0,0,800*values[1],800*values[0]];}};const graphic={parent:holder,geometricBounds:[0,0,800,800],remove:()=>{this._story.allGraphics.splice(this._story.allGraphics.indexOf(graphic),1);}};this._story.allGraphics.push(graphic);}if(scenario.table){const cells=list(['عنوان','English','مقدار','Value'].map((contents,i)=>{const para={};return {id:i,contents,texts:list([{contents,paragraphs:list([para]),applyParagraphStyle(s){this.appliedParagraphStyle=s;}}]),characters:{length:contents.length}};}));this._story.tables.push({id:100,cells,rows:list([{cells:list(cells.slice(0,2))},{cells:list(cells.slice(2))}]),columns:list([{width:100},{width:200}]),width:300});}}
    }
    function page(){const p={isValid:true,marginPreferences:{top:25,left:30,bottom:25,right:30},pageItems:list([]),get name(){return String(doc.pages.indexOf(p)+1);},remove(){doc.pages.splice(doc.pages.indexOf(p),1);},textFrames:{add(){const f=new TextFrame(p);p.pageItems.push(f);return f;}}};return p;}
    const master={isValid:true,name:'D1-Main Body',allPageItems:[]};const header=new TextFrame(null,true);header.contents='Old header';master.allPageItems.push(header);
    const pdfPreferences={properties:{pageRange:'OLD',viewPDF:true}};Object.defineProperties(pdfPreferences,{pageRange:{set(v){this.properties.pageRange=v;}},viewPDF:{set(v){this.properties.viewPDF=v;}},exportReaderSpreads:{set(v){this.properties.exportReaderSpreads=v;}}});
    const originalPdf=Object.assign({},pdfPreferences.properties); // prefs.properties in the real DOM is a snapshot
    let pdfValues=Object.assign({},originalPdf);Object.defineProperty(pdfPreferences,'properties',{get(){return Object.assign({},pdfValues);},set(v){pdfValues=Object.assign({},v);}});
    for(const name of ['IRNazanin\tRegular','IRNazanin\tBold','Modam\tExtraBold  [ @mimvid ]','Modam\tSemiBold  [ @mimvid ]','Modam\tMedium  [ @mimvid ]','Times New Roman\tRegular'])fonts.push({name,fullName:name,fontFamily:name.split('\t')[0],fontStyleName:name.split('\t')[1],status:1,isValid:true});
    const fontList=list(fonts);if(scenario.missingFont)fontList.pop();
    doc={isValid:true,documentPreferences:{facingPages:!!scenario.facing,pageWidth:595,pageHeight:842},viewPreferences:{},textDefaults:{},pages:list([]),masterSpreads:list([master]),fonts:fontList,paragraphStyles:styles,swatches:list([{name:'Black'},{name:'Paper'}]),colors:list([]),layers:list([]),metadataPreferences:{},get stories(){return list(created);},recompose(){},save(file){events.push('save');files[file.fsName]='indd';},exportFile(format,file,show,preset){events.push({format,preset:preset&&preset.name});if(scenario.pdfError&&format==='pdf')throw Error('PDF test error');files[file.fsName]=format;},close(){events.push('close');doc.isValid=false;}};
    const pg=page();pg.appliedMaster=master;doc.pages.push(pg);doc.pages.add=(where,ref)=>{const p=page();if(where==='before')doc.pages.splice(doc.pages.indexOf(ref),0,p);else doc.pages.push(p);return p;};
    doc.layers.add=o=>{doc.layers.push(o);return o;};doc.colors.add=o=>{const c=new Style(o.name);doc.colors.push(c);return c;};
    const app={fonts:fontList,pdfExportPresets:list([{name:'[High Quality Print]',isValid:true}]),pdfExportPreferences:pdfPreferences,scriptPreferences:{userInteractionLevel:9,measurementUnit:8},wordRTFImportPreferences:{removeFormatting:true},open(){events.push('open');return doc;}};
    const cfg=Object.assign({report:'/report.docx',template:'/template.idml',title:'My Report',output:'/out',cover:true},overrides);
    const ctx={REPORT_CONFIG:cfg,app,File,Folder,TextFrame,FontStatus:{INSTALLED:1},LocationOptions:{AT_END:'end',BEFORE:'before'},ExportFormat:{INDESIGN_MARKUP:'idml',PDF_TYPE:'pdf'},SaveOptions:{NO:'no'}};
    for(const en of ['KashidasOptions','MeasurementUnits','UserInteractionLevels','OpenOptions','RulerOrigin','ColorModel','ColorSpace','ContentType','Justification','VerticalJustification','HorizontalAlignment','AnchorPosition','AnchorPoint','CoordinateSpaces','ResizeMethods','StartParagraph','ListType','ParagraphDirectionOptions','StoryDirectionOptions','FirstBaseline','TableDirectionOptions','PageRange'])ctx[en]=new Proxy({},{get:(_,p)=>p});
    vm.createContext(ctx);let error=null;try{vm.runInContext(source,ctx,{timeout:5000});}catch(e){error=e;}
    return {files,events,error,result:files['/out/result.json']&&JSON.parse(files['/out/result.json']),doc,app,header,styles,pdfValues,originalPdf};
}
let r=run({mode:'validate'});assert.ifError(r.error);assert.equal(r.result.ok,true);assert.equal(r.header.contents,'Old header');assert.equal(r.events.includes('save'),false);assert.equal(r.events.at(-1),'close');assert.equal(r.result.pdfPresets[0],'[High Quality Print]');assert.equal(r.result.availableFonts.length,6);
for(const scenario of [{missingHeader:true},{missingFont:true},{facing:true}]){r=run({mode:'validate'},scenario);assert.ok(r.error);assert.equal(r.result.ok,false);assert.equal(r.events.at(-1),'close');assert.equal(r.files['/out/Review-Needed.indd'],undefined);}
r=run();assert.ifError(r.error);assert.equal(r.result.ok,true);assert.equal(r.result.headings,8);assert.equal(r.header.contents,'My Report');assert.ok(r.files['/out/Report.indd']);assert.ok(r.files['/out/Report.idml']);assert.ok(r.files['/out/Report.pdf']);assert.equal(r.app.scriptPreferences.measurementUnit,8);assert.equal(r.app.scriptPreferences.userInteractionLevel,9);assert.deepEqual(r.pdfValues,r.originalPdf);
r=run({layout:{PdfPreset:'[High Quality Print]',BodySize:14,BodyLeading:22,AccentColor:'#112233'},author:'A',subtitle:'Sub',organization:'Org',date:'2026',closeAfterBuild:true});assert.ifError(r.error);assert.equal(r.styles.itemByName('Report Body').pointSize,14);assert.equal(r.doc.metadataPreferences.author,'A');assert.equal(r.events.find(e=>e.format==='pdf').preset,'[High Quality Print]');assert.equal(r.events.at(-1),'close');
r=run({layout:{PdfPreset:'Missing'}});assert.ok(r.error);assert.equal(r.result.ok,false);assert.equal(r.files['/out/Report.pdf'],undefined);
r=run({}, {pdfError:true});assert.ok(r.error);assert.equal(r.result.ok,false);assert.ok(r.files['/out/Report.indd']);assert.ok(r.files['/out/Review-Needed.indd']);assert.deepEqual(r.pdfValues,r.originalPdf);
r=run({layout:{TocEnabled:true}});assert.ifError(r.error);assert.equal(r.result.ok,true);assert.equal(r.result.tocPages,3);const contents=r.doc.stories.find(s=>s.contents.startsWith('فهرست'));assert.ok(contents.contents.includes('Heading 1  —  5'));assert.ok(r.result.checks.some(x=>x.includes('stabilized')));
r=run({cover:false,layout:{TocEnabled:true,TocLevel2:false}});assert.ifError(r.error);assert.equal(r.result.tocPages,2);assert.equal(r.result.pages,3);
r=run({layout:{TocEnabled:true}}, {noHeadings:true});assert.ok(r.error);assert.match(r.result.message,/no matching/);
r=run({layout:{TableSize:12,TableLeading:18,TableColor:'#AABBCC',CellPadding:8,TableBorder:1,TableHeader:true,RepeatHeader:true}}, {table:true});assert.ifError(r.error);assert.equal(r.result.tables,1);let table=r.doc.stories.find(s=>s.isBody).tables[0];assert.equal(table.headerRowCount,1);assert.equal(table.cells[0].topInset,8);assert.equal(table.cells[0].topEdgeStrokeWeight,1);assert.equal(table.cells[0].verticalJustification,'CENTER_ALIGN');assert.equal(table.cells[0].texts[0].appliedParagraphStyle.pointSize,12);assert.equal(table.cells[1].texts[0].appliedParagraphStyle.name,'Report Table Header');assert.equal(table.cells[1].texts[0].paragraphs[0].paragraphDirection,'LEFT_TO_RIGHT_DIRECTION');assert.equal(table.rows[0].cells[0].fillColor.name,'Report Table Accent');assert.equal(table.rows[0].cells[0].texts[0].paragraphs[0].justification,'CENTER_ALIGN');assert.equal(table.columns[1].width/table.columns[0].width,2);
r=run({layout:{TableHeader:true,RepeatHeader:false}}, {table:true});assert.ifError(r.error);assert.equal(r.doc.stories.find(s=>s.isBody).tables[0].headerRowCount,0);
r=run({layout:{TableHeader:false}}, {table:true});assert.ifError(r.error);assert.equal(r.doc.stories.find(s=>s.isBody).tables[0].cells[0].fillColor.name,'Paper');
r=run({layout:{ImageMaxWidthPercent:50,ImageMaxHeightPercent:50,CenterInlineImages:true}},{inlineImage:true});assert.ifError(r.error);assert.equal(r.result.inlineImages,1);assert.equal(r.result.resizedImages,1);const imageHolder=r.doc.stories.find(s=>s.isBody).allGraphics[0].parent,imageHeight=imageHolder.geometricBounds[2]-imageHolder.geometricBounds[0],imageWidth=imageHolder.geometricBounds[3]-imageHolder.geometricBounds[1];assert.ok(imageWidth<=198.426);assert.ok(imageHeight<=335.906);assert.ok(Math.abs(imageWidth/imageHeight-1)<.0001);
r=run({layout:{ReplaceImagesWithPlaceholders:true,ImageMaxWidthPercent:50,ImageMaxHeightPercent:50}},{inlineImage:true});assert.ifError(r.error);assert.equal(r.result.inlineImages,1);assert.equal(r.result.imagePlaceholders,1);assert.equal(r.doc.stories.find(s=>s.isBody).allGraphics.length,0);
r=run({cancelFile:'/out/cancel.request'},{cancel:true});assert.ok(r.error);assert.match(r.result.message,/Cancelled by user/);assert.equal(r.events.at(-1),'close');assert.equal(r.files['/out/Report.pdf'],undefined);
assert.equal(/pools\s*=\s*\[doc\.fonts\s*,\s*app\.fonts\]/.test(source),false,'Do not restore the full app.fonts scan; it can stall InDesign.');
console.log('PASS: simulated validation, safe close, missing header/font/preset, metadata, selected PDF preset, failure recovery, preference restoration and multi-page TOC stabilization.');
